// ══════════════════════════════════════════════════════════════════════════
//  University of Auckland Linux User Group
//  Annual General Meeting (AGM) 2026
// ══════════════════════════════════════════════════════════════════════════
//  Compile with:  typst compile main.typ
//  (or `typst watch main.typ` while editing)
//
//  Structure follows the 2025 Extraordinary AGM deck, minus everything that
//  was specific to calling another extraordinary meeting.
//
//  Only the CONFIG block below needs editing year to year.
// ══════════════════════════════════════════════════════════════════════════

#import "theme/theme.typ": *
#import "theme/typography.typ": radius-sm, size-micro, spacing-2xs, spacing-xs
#import "@preview/tiaoma:0.3.0": qrcode as qr-encode

// ──────────────────────────────────────────────────────────────────────────
//  CONFIG
// ──────────────────────────────────────────────────────────────────────────

// Colour theme for the deck. The QR frames are drawn from the same palette.
// Options: "paper", "warm-amber", "tomorrow", "dracula".
#let colortheme = "paper"

// Date and time the AGM starts. Change this one line each year.
// (Typst wants hour, minute and second together when a time is given.)
#let agm-date = datetime(year: 2026, month: 9, day: 21, hour: 18, minute: 0, second: 0)

// The same date and time as plain text, for the title and opening slides.
#let agm-time = "6:00pm"
#let agm-venue = "University of Auckland"

// Notice of motion details. Put the submitter as written on the notice itself;
// while it is `none` the "Submitted by" line stays hidden.

// Links. Swap in the real ones before presenting. These are what the slides
// point at, so each one needs the full address including https://.
#let constitution-link = "http://link.birdmakingstuff.nz/lug-constitution-2026"
#let site-link = "https://lug.ac"
#let github-link = "https://github.com/lug-uoa"
#let discord-link = "https://discord.gg/lug-uoa" // TODO: current invite
#let minutes-link = "https://link.birdmakingstuff.nz/2025-eagm-minutes"
#let annual-report-link = "http://link.birdmakingstuff.nz/lug-2026-annual-report" // TODO: 2026 Annual Report

#let club-abbr = [LUG\@UoA]

// Every address shown on a slide goes through this, so each one is clickable.
#let weblink(address, name) = link(address)[#name]

// Where an address is worth scanning rather than typing, put a QR code under
// it. The code is generated by the `tiaoma` package and stays black on white
// whatever the colour theme is, because phone cameras need that contrast; only
// the frame around it follows the theme.
//
// - address (str): the full address to encode, including https://.
// - size (length): edge length of the code, excluding its padding.
// - caption (content): optional label under the code.
// - caption-size (length): size of that label. Body size by default so it stays
//   readable from the back of the room; pass `caption-size: size-small` to shrink it.
#let qr-code(address, size: 120pt, caption: none, caption-size: size-body) = {
  let c = get-theme-colors(theme: colortheme)

  align(center)[
    #block(
      fill: white,
      stroke: 0.5pt + c.border-subtle,
      radius: radius-sm,
      inset: spacing-xs,
    )[
      #qr-encode(
        address,
        options: ("scale": 4.0, "fg-color": black, "bg-color": white),
        width: size,
        height: size,
      )
    ]

    #if caption != none [
      #v(-8pt)
      #text(fill: c.text-secondary, size: caption-size, weight: "bold")[#caption]
    ]
  ]
}

// Every vote in the deck is put through this, so they all look and read the
// same: one box, one heading, the motion inside, and any threshold as a note.
#let vote(motion, note: none) = block(width: 100%)[
  #highlight-box(title: [*VOTE* - _all in favour raise their hands_])[
    #motion

    #if note != none [#note]
  ]
]

// ──────────────────────────────────────────────────────────────────────────
//  TREASURER'S STATEMENT
//  The figures live here, once, in the order the Treasurer's statement reads.
//  The statement is presented over two slides so the numbers stay legible from
//  the back of the room; changing a figure here changes it on both.
//
//    kind: "group"  a section band - `label`, optionally `amount`
//    kind: "line"   `label` and `amount`; `total: true` rules a line off above
//                   it and bolds the row, `strong: true` only bolds it
//    kind: "gap"    a little air between sections
// ──────────────────────────────────────────────────────────────────────────

#let treasurer-income-rows = (
  (kind: "group", label: "Account balance", amount: "NZD"),
  (kind: "line", label: "Opening account balance", amount: "$0.52"),
  (kind: "group", label: "Income"),
  (kind: "line", label: "Raspberry Pi lease", amount: "$60.00"),
  (kind: "line", label: "University of Auckland grant", amount: "$1,000.06"),
  (kind: "line", label: "Total income", amount: "$1,060.06", total: true),
  (kind: "gap"),
  (kind: "group", label: "Expenses"),
  (kind: "line", label: "No expenses paid", amount: "$0.00"),
  (kind: "line", label: "Total expenses", amount: "$0.00", total: true),
  (kind: "gap"),
  (kind: "group", label: "Profit", amount: "$1,060.06"),
  (kind: "gap", size: 2.5pt),
  (kind: "line", label: "Closing account balance", amount: "$1,060.58", total: true),
)

#let treasurer-asset-rows = (
  (kind: "group", label: "Assets", amount: "NZD"),
  (kind: "line", label: "Cash / bank balance", amount: "$1,060.58"),
  (kind: "line", label: "2x Raspberry Pi 5 (fixed assets)", amount: "$525.48"),
  (kind: "line", label: "Total assets", amount: "$1,586.06", total: true),
  (kind: "gap"),
  (kind: "group", label: "Liabilities"),
  (kind: "line", label: "Big Tuxus stickers", amount: "$43.00"),
  (kind: "line", label: "Standard stickers", amount: "$67.00"),
  (kind: "line", label: "Pizza Hut order: STK Tournament 2", amount: "$43.46"),
  (kind: "line", label: "Pizza Hut order: STK Tournament 3", amount: "$39.99"),
  (kind: "line", label: "Pizza Hut order: Self-Hosting", amount: "$50.98"),
  (kind: "line", label: "Pizza Hut order: Game Console talk", amount: "$39.99"),
  (kind: "line", label: "Pizza Hut order: NixOS talk", amount: "$50.98"),
  (kind: "line", label: "GDGCxLUG Open Source Workshop", amount: "$40.00"),
  (kind: "line", label: "St Pierre's Sushi AGM", amount: "$38.50"),
  (kind: "line", label: "Total liabilities", amount: "$414.89", total: true),
)

// Caps label used for both the section bands in the tables and the note's
// title, so the same words always look the same across the Treasurer slides.
// One text size runs through the whole statement: hierarchy comes from weight,
// colour, the tinted band and the rules, which keeps every band the same height
// and every baseline level. `accent-primary` on its own is a fill colour, too
// light to read as text; darkened it clears 4.5:1 against the band in every
// theme.
#let group-label(content) = {
  let c = get-theme-colors(theme: colortheme)
  text(
    size: size-body,
    weight: "semibold",
    tracking: tracking-wider,
    fill: c.accent-primary.darken(45%),
  )[#upper(content)]
}

// Renders either set of rows as a two-column statement: labels left, amounts
// right, sections on a tinted band. Amounts sit in the primary text colour and
// labels stay secondary, so the figures are what the eye lands on.
#let treasurer-table(rows) = {
  let c = get-theme-colors(theme: colortheme)
  let ins = (x: spacing-sm, y: 5pt)

  let cells = ()
  for row in rows {
    if row.kind == "gap" {
      // A gap row is how much air a section gets. The one before the closing
      // balance is deliberately smaller: the rule under it is drawn on the
      // row's top edge, and it needs the same clearance from the filled band
      // above as a rule following a row of text gets from that row's inset.
      cells.push(table.cell(
        colspan: 2,
        inset: (y: row.at("size", default: 4pt)),
      )[])
    } else if row.kind == "group" {
      let amount = row.at("amount", default: none)
      let band-cell(side, content) = table.cell(
        fill: c.bg-surface,
        inset: ins,
        align: side,
      )[#content]

      if amount == none {
        cells.push(table.cell(
          colspan: 2,
          fill: c.bg-surface,
          inset: ins,
          align: left,
        )[#group-label(row.label)])
      } else {
        cells.push(band-cell(left, group-label(row.label)))

        // "NZD" is the column's unit, not a figure, so it stays lighter than the
        // profit figure, which is read as a figure and carries the same weight
        // and colour as the amounts above it.
        let is-unit = amount == "NZD"
        cells.push(band-cell(right, text(
          weight: if is-unit { "medium" } else { "semibold" },
          tracking: if is-unit { tracking-wider } else { tracking-normal },
          fill: if is-unit { c.text-secondary } else { c.text-primary },
        )[#upper(amount)]))
      }
    } else {
      let is-total = row.at("total", default: false)
      let emphasised = is-total or row.at("strong", default: false)
      let rule = if is-total { (top: 0.75pt + c.border-medium) } else { none }

      cells.push(table.cell(inset: ins, stroke: rule)[
        #if emphasised { strong[#row.label] } else { row.label }
      ])
      cells.push(table.cell(inset: ins, align: right, stroke: rule)[
        #if emphasised { strong[#row.amount] } else { text(fill: c.text-primary)[#row.amount] }
      ])
    }
  }

  table(
    columns: (1fr, auto),
    column-gutter: 0pt,
    row-gutter: 0pt,
    stroke: none,
    inset: ins,
    ..cells,
  )
}

// ──────────────────────────────────────────────────────────────────────────
//  AGENDA
//  The repeated agenda tints the items already covered, so the list fills in
//  as the meeting goes on. `covered` counts the finished items.
// ──────────────────────────────────────────────────────────────────────────

#let agenda-items = (
  [Opening of Meeting],
  [Apologies],
  [Confirmation of Minutes of previous AGM],
  [Presentation of Annual Report],
  [Adoption of Annual Report],
  [Presentation of Treasurer's statement],
  [Appointment of New Honorary Members],
  [Election of New Executives and appointment of Auditor],
  [Notice(s) of Motions],
  [Conclusion],
)

#let agenda(covered: 0) = enum(
  ..agenda-items.enumerate().map(((i, item)) => if i < covered { alert(item) } else { item }),
)

// ══════════════════════════════════════════════════════════════════════════

#show: calmly.with(
  config-info(
    title: [Annual General Meeting 2026],

    author: [University of Auckland Linux User Group],
    date: agm-date,
    institution: [Waipapa Taumata Rau - University of Auckland],
  ),
  colortheme: colortheme,
)

#title-slide()

== Agenda
#agenda(covered: 0)

// ──────────────────────────────────────────────────────────────────────────
= Pre-requisites

== Why hold the Annual General Meeting (AGM)?
- Required by law: the Club is an incorporated society and has to hold one every year.
- Transparency and accountability: the Executive reports back to the membership.
- Every member gets a voice: on the reports, the elections and any notice of motion.

== The minutes
The Secretary shall record this AGM's minutes.

What the minutes are for:
- Recording the decisions the meeting makes
- Recording concerns and issues raised by members
- Keeping an attendee list

// ──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 1)

= Opening of Meeting

== The Club
- *Official name:*
  - University of Auckland Linux User Group
- *Abbreviation:*
  - #text("LUG@UoA")
- *Type of organisation:*
  - Unincorporated Society
- *Objects:*
  - to educate students about, and promote, GNU/Linux and its surrounding Free and Open Source Software (FOSS) ecosystem
- *Financial year:*
  - 1 June to 31 May

== Links
// Labels in the first grid row, each QR code and its address in the second, so
// the three codes stay on one line even though the first address wraps to two.
// Each code sits between its label and its address, nearer the address it
// opens: the grid's row gutter spaces it from the label, and the negative
// spacing below cancels most of the address line's own top spacing.

#align(horizon)[
  #grid(
    columns: (1fr, 1fr, 1fr),
    column-gutter: spacing-lg,
    row-gutter: spacing-lg,
    align: center,
    [*Constitution*], [*Website/Sign-up Form*], [*GitHub Org*],
    [
      #qr-code(constitution-link, size: 130pt)
      #v(-0.55em)
      #weblink(constitution-link, [#constitution-link])
    ],
    [
      #qr-code(site-link, size: 130pt)
      #v(-0.55em)
      #weblink(site-link, [#site-link])
    ],
    [
      #qr-code(github-link, size: 130pt)
      #v(-0.55em)
      #weblink(github-link, [#github-link])
    ],
  )]

#focus-slide[
  #text(size: 0.75em)[University of Auckland Linux User Group]

  #v(0.4em)
  Annual General Meeting (AGM) 2026

  #v(0.4em)
  *We declare this meeting open!*

  #v(0.8em)
  #text(size: 0.5em)[#agm-date.display("[month repr:long] [day], [year]") · #agm-time]
]

// ──────────────────────────────────────────────────────────────────────────
= Voting Rights

== Definitions
- *Member:* anyone who has registered to be part of the club
- *Executive member:* a member who has previously been appointed to take on additional roles within the club
- *Motion:* an issue discussed at the meeting that has been formalised and needs votes from members to move the meeting forward
- *Voting:* the democratic process of moving a motion forward

== Your right to vote
Every financial member present is entitled to one (1) vote per issue.

$ f("Exec") = f("Non-exec") $

- Raise one physical or Zoom hand to vote
- The President holds a deliberative vote, and a casting vote in the event of a tie

== Quorum and thresholds
- *Quorum:* a minimum of five (5) Management Committee members. If no quorum is present thirty (30) minutes after the time appointed, the meeting stands adjourned for one (1) week.
- *Decisions:* at least two-thirds of the attendees must have voted
- *Constitutional changes:* seventy-five percent (75%) of those present and entitled to vote (Special Resolution)

#soft-divider()

#muted[All of this is in the constitution: #weblink(constitution-link, [#constitution-link])]

// ──────────────────────────────────────────────────────────────────────────

== Agenda
#agenda(covered: 2)

== Apologies
- Missing members: apologies received are recorded in the minutes

- We recognise that this AGM has been held late on a Monday, which is not exactly the most desirable time to hold an AGM...

#v(0.5em)

#vote([To accept the apologies as recorded.])

// ──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 3)

= Confirmation of Minutes

== Previous AGM minutes
#align(horizon)[
  #two-col[
    The previous Annual General Meeting was the 2025 Extraordinary AGM, held in December 2025.

    - Minutes submitted by: the Secretary
    - Minutes available at: #weblink(minutes-link, [#minutes-link])
  ][
    #qr-code(minutes-link, size: 150pt, caption: [Scan for the minutes])
  ]]
#v(0.5em)

_Continued on next slides..._

== What the previous meeting decided
- *Amendment A:* the AGM must be held within six (6) months of the end of the financial year, before the end of semester date in the university calendar
- *Amendment B:* the financial year starts on the 1st of June each year
- *Amendment C:* removal from the Management Committee by a majority vote under a Privileges Accountability Bylaw, and general meetings may be called by members who are not on the Executive Committee
- *Amendment D:* typo fixes (_honourary_ to _honorary_)

All four are now in the constitution at #weblink(constitution-link, [#constitution-link]).

_Continued on next slides..._

== Executives confirmed at the previous meeting
- *President:* Thomas Dickson
- *Treasurer (Vice President):* Parmjot Singh
- *Secretary:* Ben Wang
\
- *General Executive Member:* Dylan Shearer
- *General Executive Member:* Jiaxin Yan
- *Auditor:* Jiaxin Yan

_Continued on next slides..._

== Previous AGM minutes
#align(horizon)[
  #two-col[
    The previous Annual General Meeting was the 2025 Extraordinary AGM, held in December 2025.

    - Minutes submitted by: the Secretary
    - Minutes available at: #weblink(minutes-link, [#minutes-link])
  ][
    #qr-code(minutes-link, size: 150pt, caption: [Scan for the minutes])
  ]]

#v(0.5em)

#vote([To confirm the minutes of the previous Annual General Meeting.])



//──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 4)

= Annual Report

== Annual Report 2026
#two-col[
  What the report covers:
  - Objects of the Club
  - Meetings and Events Held
  - Financial Summary
  - Future Outlook
  - Acknowledgements

  Available at: #weblink(annual-report-link, [#annual-report-link])
][
  #qr-code(annual-report-link, size: 150pt, caption: [Scan for the Annual Report])
]

#muted[Vote will be held after the report is presented.]

== Agenda
#agenda(covered: 5)

== Annual Report
#two-col[
  What the report covers:
  - Objects of the Club
  - Meetings and Events Held
  - Financial Summary
  - Future Outlook
  - Acknowledgements

  Available at: #weblink(annual-report-link, [#annual-report-link])
][
  #qr-code(annual-report-link, size: 150pt, caption: [Scan for the Annual Report])
]

#vote([To accept the Annual Report.])

// ──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 6)

= Treasurer's Report

== Statement of Income and Expenditure
#align(horizon)[#treasurer-table(treasurer-income-rows)]

== Statement of Assets and Liabilities
#align(horizon)[#treasurer-table(treasurer-asset-rows)]

== Notice and Vote to Accept Treasurer's Report
#align(horizon)[
  #highlight-box(title: [#group-label("Note")])[
    The Treasurer currently does not have access to the Club's bank account following the recent change of banking provider. The cash balance above is based on the latest available account information from forwarded statements. The liabilities listed above are unpaid expenses/commitments and have therefore not been included in total expenses.
  ]

  #v(spacing-md)

  #vote([To accept the Treasurer's Report.])
]

// ──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 7)

== Appointment of New Honorary Members

No Notices of Motions to appoint new honorary members were received in time for the Annual General Meeting.

== Agenda
#agenda(covered: 8)

= Election of New Executives

== Positions
The Executive positions are the same as last time:

- President
- Treasurer (Vice President)
- Secretary
- General Executive Member (multiple)

The meeting also appoints the Auditor.

#muted[Amendment A, tabled later today, would formalise more Executive roles (Events, Collaborations and Projects).]

== Executive Elections
- To elect the new Executive
- To appoint the Auditor

#v(0.4em)

#vote(
  [To elect the new Executive members and to appoint the Auditor.

    #muted[
      As a reminder, this includes:
      - President
      - Treasurer (Vice President)
      - Secretary
      - General Executive Member (multiple)
      - Auditor
    ]
  ],
  note: [Each position/member is voted on separately.],
)

// ──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 9)

= Notice(s) of Motions

== Amendment A

*Submitted by:* Jiaxin Yan\
*Date submitted:* #datetime(year: 2026, month: 9, day: 8).display("[month repr:long] [day], [year]")

Modify clause 4 in section 8 to the following:

```diff
(4) Management of the Club shall be vested in the Management Committee elected by the members at the Annual General Meeting and consisting of:

1. President
2. Secretary
3. Treasurer (Vice President)
- 4. General Executive Member (multiple)
+ 4. Events Executive
+ 5. Collaborations Executive
+ 6. General Executive Member (multiple)
```

#pagebreak()

=== Rationale
_This amendment formalises the Events Executive and Collaborations Executive roles. General Executive Member(s) are currently responsible for both of these tasks, however no single Executive Member is responsible for hosting events or maintaining collaborations with other organisations & the wider open-source community._

== Vote on Amendment A
#vote(
  [To adopt Amendment A as tabled.],
  note: [Changing the constitution needs a   seventy-five percent (75%) majority of those present and entitled to vote (section 14).],
)

== Sub-amendment A.1: Projects Executive
*Submitted by:* Jiaxin Yan\
*Date submitted:* #datetime(year: 2026, month: 9, day: 8).display("[month repr:long] [day], [year]")

Modify point 6, clause 4, section 8 to include the following:

```diff
- 6. General Executive Member (multiple)
+ 6. Projects Executive
+ 7. General Executive Member (multiple)
```

=== Rationale
The same reason as Amendment A, applied to Projects.

== Vote on Sub-amendment A.1
#vote(
  [To adopt Sub-amendment A.1.],
  note: [Same threshold as Amendment A: seventy-five percent (75%) of those present and entitled to vote (section 14).],
)

== Amendment A: final version

With the amendment and the sub-amendment carried, clause 4 in section 8 reads:

```
(4) Management of the Club shall be vested in the Management Committee elected by the members at the Annual General Meeting and consisting of:

1. President
2. Secretary
3. Treasurer (Vice President)
4. Events Executive
5. Collaborations Executive
6. General Executive Member (multiple)
```
// ──────────────────────────────────────────────────────────────────────────
== Agenda
#agenda(covered: 10)

#ending-slide(
  title: [Thank you],
  subtitle: [Please enjoy the food! We hope you have a wonderful evening.],
)
